name: Pipeline DevSecOps CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build, Scan and Detect Secrets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout de Código
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Obligatorio para Gitleaks: descarga todo el historial de commits para analizarlo

    # NUEVO PASO: Análisis de fugas de secretos (Gitleaks)
    - name: Análisis de Secretos con Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: detect --verbose

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Construir Imagen Docker
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: lromerob/app-flask:latest

    - name: Escanear Imagen con Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'lromerob/app-flask:latest'
        format: 'table'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'
